[package]
name = "jendeley-search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
serde_json = "1.0"
pdf-extract = "0.6.5"
