name: Build and Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
  release-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Releasable.Dockerfile
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./shellcheck.Dockerfile
